CREATE DATABASE STEP3_BOARD_EX;

USE STEP3_BOARD_EX;

CREATE TABLE BOARD(
	NUM INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WRITER VARCHAR(50),
    EMAIL VARCHAR(50),
    SUBJECT VARCHAR(50),
    PASSWORD VARCHAR(20),
    REG_DATE DATE,
    READ_COUNT INT,
   	CONTENT VARCHAR(200)
);

SELECT * FROM BOARD;