
CREATE DATABASE STEP4_BOARD_EX;

USE STEP4_BOARD_EX;

CREATE TABLE BOARD(
	NUM        INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WRITER 	   VARCHAR(20),
    EMAIL      VARCHAR(20),
    SUBJECT    VARCHAR(50),
    PASSWORD   VARCHAR(20),
    REG_DATE   DATE,
    REF        INT(10),             
    RE_STEP    INT(10),     	  
    RE_LEVEL   INT(10),		  
    READ_COUNT INT(10),
    CONTENT    VARCHAR(20)
);

SELECT * FROM BOARD;
